install.packages("dplyr")
library(dplyr)
install.packages("ggplot2")
library(ggplot2)
install.packages("corrplot")
library(corrplot)
data <- read.csv("https://raw.githubusercontent.com/tugceaydogan7/Taylor-Rule-tugce-/refs/heads/main/hw3%20veri.csv", , sep = ";")
ggplot(data, aes(x = real.gdp, y = inflation)) + geom_point() +  labs(title = "Scatter Plot of Real GDP vs. Inflation", x = "Real GDP", y = "Real Inflation") + theme_minimal()
inflation.gap=data$inflation-data$expected.inflation
output.gap=((data$real.gdp-data$potential.real.gdp)/data$potential.real.gdp)*100
ggplot(data, aes(x = output.gap, y = inflation.gap)) + geom_point() +  labs(title = "Scatter Plot of Output Gap vs. Inflation Gap", x = "Output Gap", y = "Inflation Gap") + theme_minimal()
ggplot(data, aes(x = nominal.interest.rate, y = expected.inflation)) + geom_point() +  labs(title = "Scatter Plot of Nominal Interest Rate vs. Expected Inflation", x = "Nominal Interest Rate", y = "Expected Inflation") + theme_minimal()
ggplot(data, aes(x = nominal.interest.rate, y = real.gdp)) + geom_point() +  labs(title = "Scatter Plot of Nominal Interest Rate vs. Real GDP", x = "Nominal Interest Rate", y = "Real GDP") + theme_minimal()
data_num= data %>% select(-year)
data_var= data %>% select(-notr.real.interest.rate)
cor(data_var)
cor_matrix <- cor(data_var %>% select_if(is.numeric), use = "complete.obs")
# Create a correlation plot 
corrplot(cor_matrix, method = "number", type = "full", order = "hclust", tl.col = "black", tl.srt = 45, addCoef.col = "black")
summary(data_num)
ggplot(data, aes(x=year)) +  geom_line(aes(y=inflation, color="Inflation")) + geom_line(aes(y=expected.inflation, color="Expected Inflation")) + labs(title="Time Series Plot")
ggplot(data, aes(x=year)) +  geom_line(aes(y=real.gdp, color="Real GDP")) + geom_line(aes(y=potential.real.gdp, color="Potential Real GDP")) + labs(title="Time Series Plot")
ggplot(data, aes(x=year)) +  geom_line(aes(y=nominal.interest.rate, color="Nominal Interest Rate")) + geom_line(aes(y=inflation, color="Inflation")) + labs(title="Time Series Plot")
ggplot(data, aes(x=year)) +  geom_line(aes(y=nominal.interest.rate, color="Nominal Interest Rate")) + geom_line(aes(y=output.gap, color="Output Gap")) + labs(title="Time Series Plot")
install.packages("ARDL")
library (ARDL)
data_nu <- data_num %>% mutate(inflation.gap = inflation-expected.inflation, output.gap = (real.gdp - potential.real.gdp) / potential.real.gdp * 100)
ardl_model <- dynlm(data$nominal.interest.rate ~ inflation.gap + output.gap )
summary(ardl_model)
ggsave("scatter_plot.png")
ggsave("time_series_plot.png")
