install.packages("dplyr")
library(dplyr)
install.packages("ggplot2")
library(ggplot2)
data <- read.csv("https://raw.githubusercontent.com/tugceaydogan7/Taylor-Rule-tugce-/refs/heads/main/hw3%20veri.csv", , sep = ";")
ggplot(data, aes(x = real.gdp, y = inflation)) + geom_point() +  labs(title = "Scatter Plot of Real GDP vs. Inflation", x = "Real GDP", y = "Real Inflation") + theme_minimal()
inflation.gap=data$inflation-data$expected.inflation
output.gap=((data$real.gdp-data$potential.real.gdp)/data$potential.real.gdp)*100
ggplot(data, aes(x = output.gap, y = inflation.gap)) + geom_point() +  labs(title = "Scatter Plot of Output Gap vs. Inflation Gap", x = "Output Gap", y = "Inflation Gap") + theme_minimal()
data_num= data %>% select(-year)
cor(data_num)
summary(data_num)
ggplot(data, aes(x=year)) +  geom_line(aes(y=inflation, color="Inflation")) + geom_line(aes(y=expected.inflation, color="Expected Inflation")) + labs(title="Time Series Plot")
ggplot(data, aes(x=year)) +  geom_line(aes(y=real.gdp, color="Real GDP")) + geom_line(aes(y=potential.real.gdp, color="Potential Real GDP")) + labs(title="Time Series Plot")
ggplot(data, aes(x=year)) +  geom_line(aes(y=nominal.interest.rate, color="Nominal Interest Rate")) + geom_line(aes(y=inflation, color="Inflation")) + labs(title="Time Series Plot")
ggplot(data, aes(x=year)) +  geom_line(aes(y=nominal.interest.rate, color="Nominal Interest Rate")) + geom_line(aes(y=output.gap, color="Output Gap")) + labs(title="Time Series Plot")
install.packages("ARDL")
library (ARDL)
data_nu <- data_num %>% mutate(inflation.gap = inflation-expected.inflation, output.gap = (real.gdp - potential.real.gdp) / potential.real.gdp * 100)

model <- auto_ardl(nominal.interest.rate ~ inflation.gap + output.gap +notr.real.interest.rate, data = data_nu, max_order=3)
summary (model)
ggsave("scatter_plot.png")
ggsave("time_series_plot.png")